apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8sforbidimageprefix
spec:
  crd:
    spec:
      names:
        kind: K8sForbidImagePrefix
      validation:
        openAPIV3Schema:
          properties:
            parameters:
              type: object
              properties:
                forbidden_prefix:
                  type: string
                suggested_prefix:
                  type: string

  targets:
  - target: admission.k8s.gatekeeper.sh
    rego: |
      package k8sforbidimageprefix

      violation[{"msg": msg}] {
        forbidden := input.parameters.forbidden_prefix
        suggested := input.parameters.suggested_prefix

        img := input.review.object.spec.template.spec.containers[_].image

        startswith(img, forbidden)

        # extract the part after forbidden_prefix
        trimmed := trim_prefix(img, forbidden)

        msg := sprintf(
          "Image '%v' is blocked. Use: '%v%v' instead.",
          [img, suggested, trimmed]
        )
      }

      startswith(s, prefix) {
        substring(s, 0, count(prefix)) == prefix
      }

      trim_prefix(full, prefix) = result {
        result := substring(full, count(prefix), count(full) - count(prefix))
      }
